name: Validate

on:
  pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7.13.2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install
      run: |
        pnpm install
    - name: Lint
      run: |
        pnpm run --filter ./gmcl-electron-app lint
        pnpm run --filter ./gmcl-keystone-ui lint
        pnpm run --filter ./gmcl-runtime lint
        pnpm run --filter ./gmcl-runtime-api lint
    - name: Check
      run: |
        pnpm run --filter ./gmcl-electron-app check
        pnpm run --filter ./gmcl-keystone-ui check
        pnpm run --filter ./gmcl-runtime check
        pnpm run --filter ./gmcl-runtime-api check
    - name: Build
      run: |
        pnpm run --prefix gmcl-keystone-ui build
        pnpm run --prefix gmcl-electron-app build